<View>
<Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true"/>
 #================================
# department and tag section
#================================  
  #----------------------
  <Header name="heading-department" value="department" />
  <Choices name="department" toName="image"
           showInLine="true" required="true"
           choice="single-radio">
    <Choice value="womens shoes"/>
    <Choice value="tag"/>
    <Choice value="other"/>
  </Choices>
  #----------------------
  <Choices name = "tag-choices" toName="image" showInLine="true"
           required="true"
           visibleWhen="choice-selected"
           whenTagName="department"
           choice="multiple"
           whenChoiceValue="tag">
    <View style="width:100%">
      <Header name="heading-tag-choice" value="what does the tag contain (Select All Applicable)" />
     
    </View>    
    <Choice value="contains brand-name"/>
    <Choice value="contains brand-logo"/>
    <Choice value="contains material"/>    
    <Choice value="contains model-number"/>    
    <Choice value="contains size"/>    
    <Choice value="contains made-in"/>    
    <Choice value="contains others"/>    
    </Choices>
#================================
# material section (insole,lining,outer-sole, upper-shoe)
#================================
  <View style="display: flex;">
  
  #----------------------
    <View style="flex: 50%">
  <Choices name="insole-material"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="department" whenChoiceValue="womens shoes" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-insole-material" value="insole material" />
     
    </View>
    <Choice value="cork"/>
    <Choice value="not_applicable"/>
  </Choices>
  </View>
  #----------------------
   <View style="flex: 50%">
  <Choices name="lining-material"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="insole-material" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-lining-material" value="lining material" />
     
    </View>
   
    <Choice value="canvas"/>
    <Choice value="fur"/>
    <Choice value="lambskin"/>
<Choice value="not_applicable"/>    
  </Choices>  
     </View>
    </View>
  #----------------------
  <View style="display: flex;">
  <Choices name="outsole-material"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="lining-material" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-outsole-material" value="outsole-material" />
     
    </View>    
    <Choice value="cork"/>
    <Choice value="rubber"/>
<Choice value="not_applicable"/>    
  </Choices>  
  #----------------------  
  <Choices name="upper-shoe-material"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="outsole-material" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-shoe-material" value="upper shoe material" />
     
    </View>
    <Choice value="cork"/>
    <Choice value="fur"/>
<Choice value="not_applicable"/>    
  </Choices>
</View>
#================================================================
# Heel and bottom of shoe section (heel-height,style,cleat)
#================================================================
  <View style="display: flex;">
    <View style="flex: 50%">
  <Choices name="heel-height"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="upper-shoe-material" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-heel-height" value="heel height" />
     
    </View>
    <Choice value="flat"/>
    <Choice value="low"/>
    <Choice value="mid"/>
    <Choice value="high"/>
    <Choice value="ultra-high"/>
<Choice value="not_applicable"/>    
  </Choices>
      </View>
  #----------------------
      <View style="flex: 50%">
  <Choices name="cleat-type"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="heel-height" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-cleat-type" value="cleat type" />
     
    </View>
    <Choice value="Plastic Cleats"/>
    <Choice value="Rubber Cleats"/>
    <Choice value="Metal Cleats"/>
<Choice value="not_applicable"/>    
  </Choices>  
  </View>
    </View>
  #----------------------
  <Choices name="heel-style"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="cleat-type" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-heel-style" value="heel style" />
     
    </View>
   
    <Choice value="block heel"/>
    <Choice value="cone heel"/>
    <Choice value="cuban heels"/>
    <Choice value="flat heels"/>
    <Choice value="Stilettos heels"/>
    <Choice value="kitten heels"/>
    <Choice value="spool heels"/>
    <Choice value="wedge heels"/>
  <Choice value="not_applicable"/>
  </Choices>  
  
#=============================
# shoe shaft and toe
#=============================
  <Choices name="shoe-shaft-style"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="heel-style" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-shoe-shaft-style" value="shoe shaft style" />
     
    </View>
    <Choice value="Ankle"/>
    <Choice value="Low Top"/>
    <Choice value="Mid Top"/>
    <Choice value="High Top"/>
    <Choice value="Mid Calf Top"/>
    <Choice value="Knee High"/>
    <Choice value="Thigh High"/>
    <Choice value="Over the Knee"/>
    <Choice value="not_applicable"/>
  </Choices>  
  #----------------------
  <Choices name="toe-shape"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="shoe-shaft-style" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-toe-shape" value="toe shape" />
     
    </View>    
  <Choice value = "pointed_toe"/>
<Choice value = "round_toe"/>
<Choice value = "square_toe"/>
<Choice value = "open_toe"/>
<Choice value = "peep_toe"/>
<Choice value = "closed_toe"/>
<Choice value = "almond_toe"/>
<Choice value="not_applicable"/>
  </Choices>  

#=============================
# closure
#=============================
<Choices name="closure"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="toe-shape" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-closure" value="closure" />
     
    </View>    
  <Choice value = "buckle"/>
<Choice value = "button"/>
<Choice value = "drawstring"/>
<Choice value = "hook"/>
 <Choice value = "lace-up/tie"/>
 <Choice value = "pull-on/slip-on"/>
 <Choice value = "snap"/>
  <Choice value = "zip"/>
  <Choice value="not_applicable"/>
  </Choices>
#=============================
# other features
#=============================
  #----------------------
  <Choices name="features"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="closure" choice="multiple">
     
    <View style="width:100%">
      <Header name="heading-features" value="features" />
     
    </View>
    <Choice value="straps"/>
    <Choice value="cap toe"/>
    <Choice value="spikes"/>
    <Choice value="wingtip"/>
    <Choice value="wheels"/>
	<Choice value="not_applicable"/>
  </Choices>
#=============================
# pattern
#=============================  
  #----------------------
  <Choices name="pattern"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="features" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-pattern" value="pattern" />
     
    </View>    
  <Choice value = "gingham/check"/>
    <Choice value = "Animal"/>
    <Choice value = "batik"/>
  <Choice value = "camouflage"/>  
    <Choice value = "chevron"/>
  <Choice value = "colorblock"/>
    <Choice value = "fair-isle"/>
<Choice value = "flecked"/>    
  <Choice value = "floral"/>
  <Choice value = "geometric"/>    
  <Choice value = "herringbone"/>
  <Choice value = "houndstooth"/>
  <Choice value = "ikat"/>
    <Choice value = "paisley"/>
    <Choice value = "patchwork"/>
  <Choice value = "pinstripe/striped"/>  
  <Choice value = "polkadot/spotted"/>
  <Choice value = "plaid"/>
    <Choice value = "solid"/>
  <Choice value = "tie-dye"/>
  <Choice value = "TODO_ombre"/>
<Choice value="not_applicable"/>
  </Choices>  

#=============================
# type and style
#=============================
    <Choices name="type"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="pattern" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-type" value="type" />
     
    </View>
    <Choice value="athletic"/>
    <Choice value="boot"/>
    <Choice value="casual"/>
      <Choice value="flat"/>
      <Choice value="heel"/>
      <Choice value="sandal"/>
      <Choice value="slipper"/>
           
  </Choices>
#................................
    <Choices name="style"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="type" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-style" value="style" />
     
    </View>
<Choice value="Ballet"/>
<Choice value="Biker"/>
<Choice value="Boat"/>
<Choice value="Bootie"/>
<Choice value="Chelsea"/>
<Choice value="Chukka/Desert"/>
<Choice value="Clog"/>
<Choice value="Combat"/>
<Choice value="Dorsay"/>
<Choice value="Espadrille"/>
<Choice value="Fisherman"/>
<Choice value="Flat"/>
<Choice value="Flip-Flop"/>
<Choice value="Gladiator"/>
<Choice value="Loafer"/>
<Choice value="Mary-Jane"/>
<Choice value="Moccassin"/>
<Choice value="Mule"/>
<Choice value="Oxford"/>
<Choice value="Platform"/>
<Choice value="Pump"/>
<Choice value="Rain-Boot"/>
<Choice value="Shearling"/>
<Choice value="Slide"/>
<Choice value="Slingback"/>
<Choice value="Slip-On"/>
<Choice value="Sneaker"/>
<Choice value="Snow-Boot"/>
<Choice value="Sock"/>
<Choice value="Strappy"/>
<Choice value="Thong"/>
<Choice value="Western"/>           
  </Choices>
  
#=============================
# fabric
#=============================

      <Choices name="fabric"
            toName="image"
            showInLine="true"
            required="true"
            visibleWhen="choice-selected"
            whenTagName="style" choice="single-radio">
     
    <View style="width:100%">
      <Header name="heading-fabric" value="fabric" />
     
    </View>

<Choice value="Blended"/>
<Choice value="Boucle"/>
<Choice value="Canvas"/>
<Choice value="Chambray/Denim"/>
<Choice value="Chiffon/Crepe"/>
<Choice value="Corduroy"/>
<Choice value="Crochet"/>
<Choice value="Down"/>
<Choice value="Dupion"/>
<Choice value="Felt"/>
<Choice value="Flannel"/>
<Choice value="Fleece"/>
<Choice value="French"/>
<Choice value="Gauze"/>
<Choice value="Georgette"/>
<Choice value="Gingham"/>
<Choice value="Grosgrain"/>
<Choice value="Jacquard"/>
<Choice value="Jersey"/>
<Choice value="Lace"/>
<Choice value="Latex"/>
<Choice value="Lawn"/>
<Choice value="Madras"/>
<Choice value="Microfiber"/>
<Choice value="Microfleece"/>
<Choice value="Moleskin"/>
<Choice value="Muslin"/>
<Choice value="Net"/>
<Choice value="Oilcloth"/>
<Choice value="Organdy"/>
<Choice value="Organza"/>
<Choice value="Ponte"/>
<Choice value="Poplin"/>
<Choice value="Ramie"/>
<Choice value="Rayon"/>
<Choice value="Satin"/>
<Choice value="Seersucker"/>
<Choice value="Selvage"/>
<Choice value="Shearling"/>
<Choice value="Silk"/>
<Choice value="Softshell"/>
<Choice value="Terry"/>
<Choice value="Tulle"/>
<Choice value="Tussah"/>
<Choice value="Tweed"/>
<Choice value="Twill"/>
<Choice value="Velour"/>
<Choice value="Velvet"/>
<Choice value="Voile"/>
<Choice value="Woven"/>
<Choice value="TODO_Damask"/>
<Choice value="TODO_Fabric"/>
<Choice value="TODO_Knit"/>
<Choice value="TODO_Mesh"/>
<Choice value="TODO_Taffeta"/>
<Choice value="TODO_Toile"/>
<Choice value="not_applicable"/>
</Choices>
</View>
